#version: "2"
#services:
#  app:
#    build: ./src_vue
#    links:
#      - db
#    ports:
#      - "80:80"
#  db:
#    image: mariadb:10.4.6
#    volumes:
#      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: scot
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password

#//user:password@db/scot

version: "2"
networks:
  scot-net:
services:
  app:
    build: ./src_vue
    volumes:
      - .:/src_vue
    links:
      - db
    ports:
      - "10017:80"
    networks:
      scot-net:
  db:
    image: mariadb:10.4.6
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./db/data_test:/var/lib/mysql

      # "database" : "mysql://user:password@db/scot" / local: "mysql://inga@0.0.0.0/scot"(config.json)
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scot
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      scot-net: