#version: "2"
#services:
#  app:
#    build: ./src_vue
#    links:
#      - db
#    ports:
#      - "80:80"
#  db:
#    image: mariadb:10.4.6
#    volumes:
#      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: scot
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password

#//user:password@db/scot

version: "2"
networks:
  scot-net:
services:
  app:
    build: ./src_vue
    volumes:
      - .:/src_vue
    links:
      - db
    ports:
      - "10017:80"
    networks:
      scot-net:
  db:
    image: mariadb:10.4.6
    volumes:
      # schema file
      - ./db/loadSchemaAndFiles.sql:/tmp/loadSchemaAndFiles.sql
      # csv files to be imported into db
      #- ./db/csv_test/datahub/:/var/lib/mysql-files/datahub/
      # entrypoint
      - ./db/docker_entrypoint.sh:/docker-entrypoint-initdb.d/docker_entrypoint.sh
      # database
      #- ./db/csv_test/data:/var/lib/mysql
      - ./db/gbooks_datahub/:/var/lib/mysql-files/datahub/
      #- ./db/loadSchemaAndFiles.sql:/docker-entrypoint-initdb.d/loadSchemaAndFiles.sql
      - ./db/gbooks_data:/var/lib/mysql
      #- ./db/fin_1990_2017.sql:/docker-entrypoint-initdb.d/fin_1990_2017.sql
      #- ./db/data_fin_test:/var/lib/mysql

      # "database" : "mysql://user:password@db/scot" / local: "mysql://inga@0.0.0.0/scot"(config.json)
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scot
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    networks:
      scot-net: